services:
    db.users.sql:
        container_name: db.users.sql
        environment:
            MSSQL_SA_PASSWORD: "gmJacHPs9QbU"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        volumes:
            - "task_sqlserver_users:/var/opt/mssql"

    db.auth.sql:
        container_name: db.auth.sql
        environment:
            MSSQL_SA_PASSWORD: "gmJacHPs9QbU"
            ACCEPT_EULA: "Y"
        ports:
            - "1434:1433"
        volumes:
            - "task_sqlserver_auth:/var/opt/mssql"

    db.task.sql:
        container_name: db.task.sql
        environment:
            MSSQL_SA_PASSWORD: "gmJacHPs9QbU"
            ACCEPT_EULA: "Y"
        ports:
            - "1435:1433"
        volumes:
            - "task_sqlserver_task:/var/opt/mssql"

    ms.auth.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8000
            - ASPNETCORE_HTTPS_PORTS=8001
            - "Communication:EventBus:HostName=ms.rabbitmq"
        ports:
            - "8000:8000"
            - "8001:8001"

        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
        depends_on:
            - db.auth.sql
            - ms.rabbitmq

    ms.user.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8010
            - ASPNETCORE_HTTPS_PORTS=8011
            - "Communication:EventBus:HostName=ms.rabbitmq"
        ports:
            - "8010:8010"
            - "8011:8011"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
        depends_on:
            - db.users.sql
            - ms.rabbitmq
            - ms.auth.api
    
    ms.task.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8020
            - ASPNETCORE_HTTPS_PORTS=8021
            - "Communication:EventBus:HostName=ms.rabbitmq"
        ports:
            - "8020:8020"
            - "8021:8021"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

    ms.rabbitmq:
        container_name: ms.rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"

    ms.apigateway.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_HTTP_PORTS=8030
            - ASPNETCORE_HTTPS_PORTS=8031
        ports:
            - "8030:8030"
            - "8031:8031"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
        depends_on:
            - ms.auth.api
            - ms.user.api
            - ms.task.api 