# See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["ms.task/ms.task.api/ms.task.api.csproj", "ms.task/ms.task.api/"]
COPY ["ms.task/ms.task.application/ms.task.application/ms.task.application.csproj", "ms.task/ms.task.application/ms.task.application/"]
COPY ["ms.task/ms.task.domain/ms.task.domain/ms.task.domain.csproj", "ms.task/ms.task.domain/ms.task.domain/"]
COPY ["ms.task/ms.task.infrastructure/ms.task.infrastructure/ms.task.infrastructure.csproj", "ms.task/ms.task.infrastructure/ms.task.infrastructure/"]
RUN dotnet restore "./ms.task/ms.task.api/ms.task.api.csproj"
COPY . .
WORKDIR "/src/ms.task/ms.task.api"
RUN dotnet build "./ms.task.api.csproj" -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./ms.task.api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "ms.task.api.dll"]